/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as OfficeFootballPoolRouteImport } from './routes/office-football-pool'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedCollegeRouteImport } from './routes/_authenticated/college'
import { Route as AuthenticatedCommissionerRouteImport } from './routes/_authenticated/commissioner'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDuelsRouteImport } from './routes/_authenticated/duels'
import { Route as AuthenticatedLeaderboardRouteImport } from './routes/_authenticated/leaderboard'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as JoinCodeRouteImport } from './routes/join.$code'
import { Route as AuthenticatedLeaguesIndexRouteImport } from './routes/_authenticated/leagues.index'
import { Route as AuthenticatedLeaguesLeagueIdRouteImport } from './routes/_authenticated/leagues.$leagueId'
import { Route as ApiPublicCfbSyncRouteImport } from './routes/api/public/cfb-sync'
import { Route as ApiPublicNflSyncRouteImport } from './routes/api/public/nfl-sync'
import { Route as ApiPublicRorkDuelsRouteImport } from './routes/api/public/rork-duels'
import { Route as ApiPublicRorkLeaguesRouteImport } from './routes/api/public/rork-leagues'
import { Route as ApiPublicRorkPicksRouteImport } from './routes/api/public/rork-picks'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'
import { Route as ApiPublicSznMembershipSyncRouteImport } from './routes/api/public/szn-membership-sync'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeFootballPoolRoute = OfficeFootballPoolRouteImport.update({
  id: '/office-football-pool',
  path: '/office-football-pool',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCollegeRoute = AuthenticatedCollegeRouteImport.update({
  id: '/college',
  path: '/college',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommissionerRoute =
  AuthenticatedCommissionerRouteImport.update({
    id: '/commissioner',
    path: '/commissioner',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDuelsRoute = AuthenticatedDuelsRouteImport.update({
  id: '/duels',
  path: '/duels',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeaderboardRoute =
  AuthenticatedLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const JoinCodeRoute = JoinCodeRouteImport.update({
  id: '/join/$code',
  path: '/join/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLeaguesIndexRoute =
  AuthenticatedLeaguesIndexRouteImport.update({
    id: '/leagues/',
    path: '/leagues/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeaguesLeagueIdRoute =
  AuthenticatedLeaguesLeagueIdRouteImport.update({
    id: '/leagues/$leagueId',
    path: '/leagues/$leagueId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicCfbSyncRoute = ApiPublicCfbSyncRouteImport.update({
  id: '/api/public/cfb-sync',
  path: '/api/public/cfb-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNflSyncRoute = ApiPublicNflSyncRouteImport.update({
  id: '/api/public/nfl-sync',
  path: '/api/public/nfl-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRorkDuelsRoute = ApiPublicRorkDuelsRouteImport.update({
  id: '/api/public/rork-duels',
  path: '/api/public/rork-duels',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRorkLeaguesRoute = ApiPublicRorkLeaguesRouteImport.update({
  id: '/api/public/rork-leagues',
  path: '/api/public/rork-leagues',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRorkPicksRoute = ApiPublicRorkPicksRouteImport.update({
  id: '/api/public/rork-picks',
  path: '/api/public/rork-picks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSznMembershipSyncRoute =
  ApiPublicSznMembershipSyncRouteImport.update({
    id: '/api/public/szn-membership-sync',
    path: '/api/public/szn-membership-sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/office-football-pool': typeof OfficeFootballPoolRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/college': typeof AuthenticatedCollegeRoute
  '/commissioner': typeof AuthenticatedCommissionerRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/duels': typeof AuthenticatedDuelsRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/join/$code': typeof JoinCodeRoute
  '/leagues/$leagueId': typeof AuthenticatedLeaguesLeagueIdRoute
  '/api/public/cfb-sync': typeof ApiPublicCfbSyncRoute
  '/api/public/nfl-sync': typeof ApiPublicNflSyncRoute
  '/api/public/rork-duels': typeof ApiPublicRorkDuelsRoute
  '/api/public/rork-leagues': typeof ApiPublicRorkLeaguesRoute
  '/api/public/rork-picks': typeof ApiPublicRorkPicksRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/api/public/szn-membership-sync': typeof ApiPublicSznMembershipSyncRoute
  '/leagues/': typeof AuthenticatedLeaguesIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/office-football-pool': typeof OfficeFootballPoolRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/college': typeof AuthenticatedCollegeRoute
  '/commissioner': typeof AuthenticatedCommissionerRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/duels': typeof AuthenticatedDuelsRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/join/$code': typeof JoinCodeRoute
  '/leagues/$leagueId': typeof AuthenticatedLeaguesLeagueIdRoute
  '/api/public/cfb-sync': typeof ApiPublicCfbSyncRoute
  '/api/public/nfl-sync': typeof ApiPublicNflSyncRoute
  '/api/public/rork-duels': typeof ApiPublicRorkDuelsRoute
  '/api/public/rork-leagues': typeof ApiPublicRorkLeaguesRoute
  '/api/public/rork-picks': typeof ApiPublicRorkPicksRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/api/public/szn-membership-sync': typeof ApiPublicSznMembershipSyncRoute
  '/leagues': typeof AuthenticatedLeaguesIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/office-football-pool': typeof OfficeFootballPoolRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/college': typeof AuthenticatedCollegeRoute
  '/_authenticated/commissioner': typeof AuthenticatedCommissionerRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/duels': typeof AuthenticatedDuelsRoute
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/join/$code': typeof JoinCodeRoute
  '/_authenticated/leagues/$leagueId': typeof AuthenticatedLeaguesLeagueIdRoute
  '/api/public/cfb-sync': typeof ApiPublicCfbSyncRoute
  '/api/public/nfl-sync': typeof ApiPublicNflSyncRoute
  '/api/public/rork-duels': typeof ApiPublicRorkDuelsRoute
  '/api/public/rork-leagues': typeof ApiPublicRorkLeaguesRoute
  '/api/public/rork-picks': typeof ApiPublicRorkPicksRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/api/public/szn-membership-sync': typeof ApiPublicSznMembershipSyncRoute
  '/_authenticated/leagues/': typeof AuthenticatedLeaguesIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/office-football-pool'
    | '/sitemap.xml'
    | '/college'
    | '/commissioner'
    | '/dashboard'
    | '/duels'
    | '/leaderboard'
    | '/profile'
    | '/join/$code'
    | '/leagues/$leagueId'
    | '/api/public/cfb-sync'
    | '/api/public/nfl-sync'
    | '/api/public/rork-duels'
    | '/api/public/rork-leagues'
    | '/api/public/rork-picks'
    | '/api/public/stripe-webhook'
    | '/api/public/szn-membership-sync'
    | '/leagues/'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/office-football-pool'
    | '/sitemap.xml'
    | '/college'
    | '/commissioner'
    | '/dashboard'
    | '/duels'
    | '/leaderboard'
    | '/profile'
    | '/join/$code'
    | '/leagues/$leagueId'
    | '/api/public/cfb-sync'
    | '/api/public/nfl-sync'
    | '/api/public/rork-duels'
    | '/api/public/rork-leagues'
    | '/api/public/rork-picks'
    | '/api/public/stripe-webhook'
    | '/api/public/szn-membership-sync'
    | '/leagues'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/office-football-pool'
    | '/sitemap.xml'
    | '/_authenticated/college'
    | '/_authenticated/commissioner'
    | '/_authenticated/dashboard'
    | '/_authenticated/duels'
    | '/_authenticated/leaderboard'
    | '/_authenticated/profile'
    | '/join/$code'
    | '/_authenticated/leagues/$leagueId'
    | '/api/public/cfb-sync'
    | '/api/public/nfl-sync'
    | '/api/public/rork-duels'
    | '/api/public/rork-leagues'
    | '/api/public/rork-picks'
    | '/api/public/stripe-webhook'
    | '/api/public/szn-membership-sync'
    | '/_authenticated/leagues/'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  OfficeFootballPoolRoute: typeof OfficeFootballPoolRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  JoinCodeRoute: typeof JoinCodeRoute
  ApiPublicCfbSyncRoute: typeof ApiPublicCfbSyncRoute
  ApiPublicNflSyncRoute: typeof ApiPublicNflSyncRoute
  ApiPublicRorkDuelsRoute: typeof ApiPublicRorkDuelsRoute
  ApiPublicRorkLeaguesRoute: typeof ApiPublicRorkLeaguesRoute
  ApiPublicRorkPicksRoute: typeof ApiPublicRorkPicksRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
  ApiPublicSznMembershipSyncRoute: typeof ApiPublicSznMembershipSyncRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office-football-pool': {
      id: '/office-football-pool'
      path: '/office-football-pool'
      fullPath: '/office-football-pool'
      preLoaderRoute: typeof OfficeFootballPoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/college': {
      id: '/_authenticated/college'
      path: '/college'
      fullPath: '/college'
      preLoaderRoute: typeof AuthenticatedCollegeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/commissioner': {
      id: '/_authenticated/commissioner'
      path: '/commissioner'
      fullPath: '/commissioner'
      preLoaderRoute: typeof AuthenticatedCommissionerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/duels': {
      id: '/_authenticated/duels'
      path: '/duels'
      fullPath: '/duels'
      preLoaderRoute: typeof AuthenticatedDuelsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/join/$code': {
      id: '/join/$code'
      path: '/join/$code'
      fullPath: '/join/$code'
      preLoaderRoute: typeof JoinCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/leagues/': {
      id: '/_authenticated/leagues/'
      path: '/leagues'
      fullPath: '/leagues/'
      preLoaderRoute: typeof AuthenticatedLeaguesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leagues/$leagueId': {
      id: '/_authenticated/leagues/$leagueId'
      path: '/leagues/$leagueId'
      fullPath: '/leagues/$leagueId'
      preLoaderRoute: typeof AuthenticatedLeaguesLeagueIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/cfb-sync': {
      id: '/api/public/cfb-sync'
      path: '/api/public/cfb-sync'
      fullPath: '/api/public/cfb-sync'
      preLoaderRoute: typeof ApiPublicCfbSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/nfl-sync': {
      id: '/api/public/nfl-sync'
      path: '/api/public/nfl-sync'
      fullPath: '/api/public/nfl-sync'
      preLoaderRoute: typeof ApiPublicNflSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/rork-duels': {
      id: '/api/public/rork-duels'
      path: '/api/public/rork-duels'
      fullPath: '/api/public/rork-duels'
      preLoaderRoute: typeof ApiPublicRorkDuelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/rork-leagues': {
      id: '/api/public/rork-leagues'
      path: '/api/public/rork-leagues'
      fullPath: '/api/public/rork-leagues'
      preLoaderRoute: typeof ApiPublicRorkLeaguesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/rork-picks': {
      id: '/api/public/rork-picks'
      path: '/api/public/rork-picks'
      fullPath: '/api/public/rork-picks'
      preLoaderRoute: typeof ApiPublicRorkPicksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/szn-membership-sync': {
      id: '/api/public/szn-membership-sync'
      path: '/api/public/szn-membership-sync'
      fullPath: '/api/public/szn-membership-sync'
      preLoaderRoute: typeof ApiPublicSznMembershipSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCollegeRoute: typeof AuthenticatedCollegeRoute
  AuthenticatedCommissionerRoute: typeof AuthenticatedCommissionerRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDuelsRoute: typeof AuthenticatedDuelsRoute
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedLeaguesLeagueIdRoute: typeof AuthenticatedLeaguesLeagueIdRoute
  AuthenticatedLeaguesIndexRoute: typeof AuthenticatedLeaguesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCollegeRoute: AuthenticatedCollegeRoute,
  AuthenticatedCommissionerRoute: AuthenticatedCommissionerRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDuelsRoute: AuthenticatedDuelsRoute,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedLeaguesLeagueIdRoute: AuthenticatedLeaguesLeagueIdRoute,
  AuthenticatedLeaguesIndexRoute: AuthenticatedLeaguesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  OfficeFootballPoolRoute: OfficeFootballPoolRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  JoinCodeRoute: JoinCodeRoute,
  ApiPublicCfbSyncRoute: ApiPublicCfbSyncRoute,
  ApiPublicNflSyncRoute: ApiPublicNflSyncRoute,
  ApiPublicRorkDuelsRoute: ApiPublicRorkDuelsRoute,
  ApiPublicRorkLeaguesRoute: ApiPublicRorkLeaguesRoute,
  ApiPublicRorkPicksRoute: ApiPublicRorkPicksRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
  ApiPublicSznMembershipSyncRoute: ApiPublicSznMembershipSyncRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
