/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as OfficeFootballPoolRouteImport } from './routes/office-football-pool'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedCommissionerRouteImport } from './routes/_authenticated/commissioner'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedLeaderboardRouteImport } from './routes/_authenticated/leaderboard'
import { Route as AuthenticatedLeaguesIndexRouteImport } from './routes/_authenticated/leagues.index'
import { Route as AuthenticatedLeaguesLeagueIdRouteImport } from './routes/_authenticated/leagues.$leagueId'
import { Route as ApiPublicNflSyncRouteImport } from './routes/api/public/nfl-sync'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeFootballPoolRoute = OfficeFootballPoolRouteImport.update({
  id: '/office-football-pool',
  path: '/office-football-pool',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCommissionerRoute =
  AuthenticatedCommissionerRouteImport.update({
    id: '/commissioner',
    path: '/commissioner',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeaderboardRoute =
  AuthenticatedLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeaguesIndexRoute =
  AuthenticatedLeaguesIndexRouteImport.update({
    id: '/leagues/',
    path: '/leagues/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeaguesLeagueIdRoute =
  AuthenticatedLeaguesLeagueIdRouteImport.update({
    id: '/leagues/$leagueId',
    path: '/leagues/$leagueId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicNflSyncRoute = ApiPublicNflSyncRouteImport.update({
  id: '/api/public/nfl-sync',
  path: '/api/public/nfl-sync',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/office-football-pool': typeof OfficeFootballPoolRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/commissioner': typeof AuthenticatedCommissionerRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/leagues/$leagueId': typeof AuthenticatedLeaguesLeagueIdRoute
  '/api/public/nfl-sync': typeof ApiPublicNflSyncRoute
  '/leagues/': typeof AuthenticatedLeaguesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/office-football-pool': typeof OfficeFootballPoolRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/commissioner': typeof AuthenticatedCommissionerRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/leagues/$leagueId': typeof AuthenticatedLeaguesLeagueIdRoute
  '/api/public/nfl-sync': typeof ApiPublicNflSyncRoute
  '/leagues': typeof AuthenticatedLeaguesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/office-football-pool': typeof OfficeFootballPoolRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/commissioner': typeof AuthenticatedCommissionerRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/_authenticated/leagues/$leagueId': typeof AuthenticatedLeaguesLeagueIdRoute
  '/api/public/nfl-sync': typeof ApiPublicNflSyncRoute
  '/_authenticated/leagues/': typeof AuthenticatedLeaguesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/office-football-pool'
    | '/sitemap.xml'
    | '/commissioner'
    | '/dashboard'
    | '/leaderboard'
    | '/leagues/$leagueId'
    | '/api/public/nfl-sync'
    | '/leagues/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/office-football-pool'
    | '/sitemap.xml'
    | '/commissioner'
    | '/dashboard'
    | '/leaderboard'
    | '/leagues/$leagueId'
    | '/api/public/nfl-sync'
    | '/leagues'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/office-football-pool'
    | '/sitemap.xml'
    | '/_authenticated/commissioner'
    | '/_authenticated/dashboard'
    | '/_authenticated/leaderboard'
    | '/_authenticated/leagues/$leagueId'
    | '/api/public/nfl-sync'
    | '/_authenticated/leagues/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  OfficeFootballPoolRoute: typeof OfficeFootballPoolRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicNflSyncRoute: typeof ApiPublicNflSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office-football-pool': {
      id: '/office-football-pool'
      path: '/office-football-pool'
      fullPath: '/office-football-pool'
      preLoaderRoute: typeof OfficeFootballPoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/commissioner': {
      id: '/_authenticated/commissioner'
      path: '/commissioner'
      fullPath: '/commissioner'
      preLoaderRoute: typeof AuthenticatedCommissionerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leagues/': {
      id: '/_authenticated/leagues/'
      path: '/leagues'
      fullPath: '/leagues/'
      preLoaderRoute: typeof AuthenticatedLeaguesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leagues/$leagueId': {
      id: '/_authenticated/leagues/$leagueId'
      path: '/leagues/$leagueId'
      fullPath: '/leagues/$leagueId'
      preLoaderRoute: typeof AuthenticatedLeaguesLeagueIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/nfl-sync': {
      id: '/api/public/nfl-sync'
      path: '/api/public/nfl-sync'
      fullPath: '/api/public/nfl-sync'
      preLoaderRoute: typeof ApiPublicNflSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCommissionerRoute: typeof AuthenticatedCommissionerRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRoute
  AuthenticatedLeaguesLeagueIdRoute: typeof AuthenticatedLeaguesLeagueIdRoute
  AuthenticatedLeaguesIndexRoute: typeof AuthenticatedLeaguesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCommissionerRoute: AuthenticatedCommissionerRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRoute,
  AuthenticatedLeaguesLeagueIdRoute: AuthenticatedLeaguesLeagueIdRoute,
  AuthenticatedLeaguesIndexRoute: AuthenticatedLeaguesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  OfficeFootballPoolRoute: OfficeFootballPoolRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicNflSyncRoute: ApiPublicNflSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
